Remove Google Drive Links
tetrabiodistributed/tetra pull request #34
Opened 2020-07-23 02:09 UTC by chrismolinari456

Fixes #4 

In addition to removing the Google Drive links from the references, this pull request includes several minor changes:
- Removing the bullet points from references, which caused links to appear twice on the page
- Links added to the UML diagram of the splitter assembly, as well as @Burhan-Q 's hardware requirement's list
-Minor capitalization/ description changes

2020-07-26 02:52 UTC, capsulecorplab requested changes
Sorry for the delayed review! Changes look good, though I would replace _UML_ with _SysML_

2020-07-26 02:56 UTC, capsulecorplab commented on content/en/references/ibd-system-electronic-sensing-system-dataflow.adoc
> +  UML diagram of Project Tetra's electronic sensing system.
I would re-title the description to _Interface control document for electronic sensing system_

2020-07-26 02:56 UTC, capsulecorplab commented on content/en/references/ibd-system-ventilator-splitter-assembly-airflow.adoc
> +  UML diagram of the Project Tetra splitter assembly.
I would re-title the description to _Interface control document for ventilator splitter assembly_

2020-07-27 23:12 UTC, capsulecorplab requested changes
One last change; should be good to go from there!

2020-07-27 23:12 UTC, capsulecorplab commented on content/en/references/_index.adoc
> +link:hardware_requirements.adoc[Hardware Requirements List]
You can actually remove these links (line 10-12), since Docsy will create links to the nested pages automatically.

2020-07-29 02:48 UTC, chrismolinari456 commented
Sorry for the wait; should be good to go now @capsulecorplab!

2020-07-29 07:26 UTC, capsulecorplab approved these changes

2020-07-29 07:27 UTC, merged